### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by atherdon** [CrobbitLucy/Colt-Steele-Bootcamp-Exercise#1]
Hi @CrobbitLucy, i find this repository and decided to write you a message. My name is Arthur and I'm a founder of a small startup(Groceristar). Will you be interested to contribute to our open source projects and gain some experience in startup?
This is accounts of our organizations: [ChickenKyiv](https://github.com/ChickenKyiv) and [Groceristar](https://github.com/GroceriStar)
This is our AngelList account: https://angel.co/groceristar
This is our Medium blog: https://medium.com/groceristar

Tell me what do you think,
Arthur

**Comment by CrobbitLucy** [comment]
It will be awesome, but please know that I got no experience in programming. Anyway I'll check your project often and see what I can do. Thanks.

**Comment by atherdon** [comment]
@CrobbitLucy it's ok that you don't have actual experience in coding. this
is why i find you and other newbies.
i think real project will help you to grow as software developer more
quickly.
and you'll be able to help a young company. we're at early stages and
working without funding, so your help will help us to move our project to
our goal more quickly. I saw your skills in this project and i'll try to
create tasks for you, that wouldn't be very complex. But for sure, if
you'll find out that task is created not clear or you need an additional
explanation - you just ask. So my main idea will be to extend your skills
and by creating small tasks for developer newbies, move my project forward.
I'm preparing this tasks right now. And it'll be a bit boring, but you'll
start to know more about our projects by going a small steps.

Btw, if you can star 2 of our main projects - this will help us to start
crowdfunding program and hopefully soon we'll be able to pay for our coding
work.
https://github.com/GroceriStar/groceristar
https://github.com/ChickenKyiv/recipe-api-only

Thank you for this opportunity,
Arthur
